[phases.setup]
nixPkgs = ["python311", "gcc", "glib", "libGL", "libglvnd"]
nixLibs = ["glib", "libGL", "libglvnd"]

[phases.install]
cmds = [
  "python3.11 -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
