"""
PDF Report Generator for Clinicians

Generates comprehensive, professional PDF reports with:
- Lesion images
- Risk assessment results
- Visual analysis
- Recommendations
- Clear disclaimers
"""

from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, List
import numpy as np
from PIL import Image
import io

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image as RLImage, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

from src.risk_assessment.scorer import RiskScore, RiskLevel


class ClinicalReportGenerator:
    """
    Generates PDF reports for lesion pre-screening results.
    """

    def __init__(self, output_path: str, page_size=letter):
        """
        Initialize the report generator.

        Args:
            output_path: Path where PDF will be saved
            page_size: Page size (default: letter)
        """
        self.output_path = output_path
        self.page_size = page_size
        self.doc = SimpleDocTemplate(
            output_path,
            pagesize=page_size,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch,
        )
        self.styles = getSampleStyleSheet()
        self.story = []

        # Custom styles
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Set up custom paragraph styles."""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a5490'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))

        # Disclaimer style
        self.styles.add(ParagraphStyle(
            name='Disclaimer',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.red,
            spaceAfter=12,
            spaceBefore=12,
            borderWidth=2,
            borderColor=colors.red,
            borderPadding=10,
            fontName='Helvetica-Bold',
            alignment=TA_CENTER
        ))

        # Risk level style
        self.styles.add(ParagraphStyle(
            name='RiskLevel',
            parent=self.styles['Heading2'],
            fontSize=18,
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))

        # Section heading
        self.styles.add(ParagraphStyle(
            name='SectionHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1a5490'),
            spaceAfter=12,
            spaceBefore=16,
            fontName='Helvetica-Bold'
        ))

    def add_header(self, patient_id: Optional[str] = None):
        """Add report header with title and disclaimer."""
        # Title
        title = Paragraph(
            "Lesion Pre-Screening Report",
            self.styles['CustomTitle']
        )
        self.story.append(title)

        # CRITICAL DISCLAIMER
        disclaimer_text = """
        <b>⚠️ NOT FOR MEDICAL DIAGNOSIS ⚠️</b><br/>
        This report is generated by an AI system for DOCUMENTATION and PRE-SCREENING purposes only.<br/>
        It is NOT a substitute for professional medical diagnosis or advice.<br/>
        Always consult a qualified dermatologist or healthcare professional.
        """
        disclaimer = Paragraph(disclaimer_text, self.styles['Disclaimer'])
        self.story.append(disclaimer)
        self.story.append(Spacer(1, 0.2*inch))

        # Report metadata
        metadata_data = [
            ['Report Date:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ['Report Type:', 'AI-Assisted Pre-Screening'],
        ]

        if patient_id:
            metadata_data.insert(1, ['Patient ID:', patient_id])

        metadata_table = Table(metadata_data, colWidths=[2*inch, 4*inch])
        metadata_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        self.story.append(metadata_table)
        self.story.append(Spacer(1, 0.3*inch))

    def add_image(self, image_path: str, caption: str = "Lesion Image", width: float = 4*inch):
        """
        Add image to report.

        Args:
            image_path: Path to image file
            caption: Image caption
            width: Image width in inches
        """
        try:
            img = RLImage(image_path, width=width)
            # Maintain aspect ratio
            img_pil = Image.open(image_path)
            aspect = img_pil.height / img_pil.width
            img.height = width * aspect

            self.story.append(img)

            caption_para = Paragraph(f"<i>{caption}</i>", self.styles['Normal'])
            self.story.append(caption_para)
            self.story.append(Spacer(1, 0.2*inch))
        except Exception as e:
            error_text = Paragraph(f"<i>Error loading image: {str(e)}</i>", self.styles['Normal'])
            self.story.append(error_text)
            self.story.append(Spacer(1, 0.2*inch))

    def add_risk_assessment(self, risk_score: RiskScore):
        """
        Add risk assessment section.

        Args:
            risk_score: RiskScore object with assessment results
        """
        section_title = Paragraph("Risk Assessment", self.styles['SectionHeading'])
        self.story.append(section_title)

        # Risk level with color coding
        risk_color = self._get_risk_color(risk_score.risk_level)
        risk_text = f'<font color="{risk_color}"><b>Risk Level: {risk_score.risk_level.value}</b></font>'
        risk_para = Paragraph(risk_text, self.styles['RiskLevel'])
        self.story.append(risk_para)

        # Overall score
        score_data = [
            ['Overall Risk Score:', f'{risk_score.overall_score:.1f} / 100'],
            ['Model Confidence:', f'{risk_score.confidence:.1%}'],
        ]

        score_table = Table(score_data, colWidths=[2.5*inch, 2*inch])
        score_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        self.story.append(score_table)
        self.story.append(Spacer(1, 0.2*inch))

    def add_risk_factors(self, risk_score: RiskScore):
        """
        Add detailed risk factors breakdown.

        Args:
            risk_score: RiskScore object
        """
        section_title = Paragraph("Risk Factors Analysis", self.styles['SectionHeading'])
        self.story.append(section_title)

        # Prepare risk factors table
        factors_data = [['Factor', 'Score', 'Interpretation']]

        # Model prediction
        if 'predicted_class' in risk_score.factors:
            factors_data.append([
                'Predicted Class',
                risk_score.factors['predicted_class'],
                'AI model classification'
            ])

        # Visual features
        visual_factors = {
            'visual_asymmetry': ('Asymmetry', 'ABCDE Criterion A'),
            'visual_border': ('Border Irregularity', 'ABCDE Criterion B'),
            'visual_color': ('Color Variation', 'ABCDE Criterion C'),
        }

        for key, (name, description) in visual_factors.items():
            if key in risk_score.factors:
                value = risk_score.factors[key]
                score_str = f'{value:.2f}'
                interpretation = self._interpret_visual_score(value)
                factors_data.append([name, score_str, f'{interpretation} - {description}'])

        # Create table
        factors_table = Table(factors_data, colWidths=[2*inch, 1*inch, 3*inch])
        factors_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5490')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        self.story.append(factors_table)
        self.story.append(Spacer(1, 0.2*inch))

    def add_recommendations(self, recommendations: List[str]):
        """
        Add recommendations section.

        Args:
            recommendations: List of recommendation strings
        """
        section_title = Paragraph("Recommendations", self.styles['SectionHeading'])
        self.story.append(section_title)

        for i, rec in enumerate(recommendations, 1):
            rec_text = f"<b>{i}.</b> {rec}"
            rec_para = Paragraph(rec_text, self.styles['BodyText'])
            self.story.append(rec_para)
            self.story.append(Spacer(1, 0.1*inch))

    def add_footer(self):
        """Add footer with additional disclaimers and information."""
        self.story.append(Spacer(1, 0.3*inch))

        footer_text = """
        <b>Important Notes:</b><br/>
        • This analysis is based on image processing and machine learning algorithms.<br/>
        • The system has limitations and may not detect all concerning features.<br/>
        • Only a qualified medical professional can provide a definitive diagnosis.<br/>
        • If you have any concerns about your skin, please consult a dermatologist.<br/>
        • Early detection of skin cancer significantly improves treatment outcomes.<br/>
        <br/>
        <b>About the System:</b><br/>
        This pre-screening system uses Convolutional Neural Networks (CNN) trained on dermatological images.
        It evaluates lesions based on visual features and provides risk quantification for documentation purposes.
        The system should be used as a supplementary tool in conjunction with professional medical evaluation.
        <br/><br/>
        <i>Generated by Lesion Pre-Screening CNN System v0.1.0</i>
        """

        footer = Paragraph(footer_text, self.styles['Normal'])
        self.story.append(footer)

    def generate(self):
        """Build and save the PDF report."""
        self.doc.build(self.story)
        return self.output_path

    def _get_risk_color(self, risk_level: RiskLevel) -> str:
        """Get color for risk level."""
        color_map = {
            RiskLevel.LOW: '#28a745',      # Green
            RiskLevel.MODERATE: '#ffc107',  # Yellow
            RiskLevel.HIGH: '#fd7e14',      # Orange
            RiskLevel.VERY_HIGH: '#dc3545',  # Red
        }
        return color_map.get(risk_level, '#000000')

    def _interpret_visual_score(self, score: float) -> str:
        """Interpret a visual feature score."""
        if score < 0.3:
            return "Low concern"
        elif score < 0.6:
            return "Moderate concern"
        else:
            return "High concern"


def generate_clinical_report(
    image_path: str,
    risk_score: RiskScore,
    output_path: str,
    patient_id: Optional[str] = None
) -> str:
    """
    Convenience function to generate a complete clinical report.

    Args:
        image_path: Path to lesion image
        risk_score: RiskScore object with assessment results
        output_path: Path where PDF will be saved
        patient_id: Optional patient identifier

    Returns:
        Path to generated PDF
    """
    generator = ClinicalReportGenerator(output_path)

    # Build report
    generator.add_header(patient_id=patient_id)
    generator.add_image(image_path, caption="Submitted Lesion Image")
    generator.add_risk_assessment(risk_score)
    generator.add_risk_factors(risk_score)
    generator.add_recommendations(risk_score.recommendations)
    generator.add_footer()

    # Generate PDF
    return generator.generate()


if __name__ == "__main__":
    # Example usage
    from src.risk_assessment.scorer import RiskScore, RiskLevel

    # Create sample risk score
    sample_risk = RiskScore(
        overall_score=65.5,
        risk_level=RiskLevel.HIGH,
        confidence=0.85,
        factors={
            'predicted_class': 'suspicious',
            'model_confidence': 0.85,
            'visual_asymmetry': 0.7,
            'visual_border': 0.6,
            'visual_color': 0.8,
        },
        recommendations=[
            "HIGH RISK - Seek professional medical evaluation soon.",
            "Schedule dermatologist appointment within 1-2 weeks.",
        ]
    )

    # Generate report
    print("Generating sample report...")
    # Note: Would need an actual image path for real usage
    # generate_clinical_report('path/to/image.jpg', sample_risk, 'sample_report.pdf')
    print("Report generation code ready!")
